# Generated by Django 2.2.3 on 2019-08-03 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('PREPAID', 'prepaid plan type'), ('POSTPAID', 'postpaid plan type'), ('DONGLE', 'dongle plan type')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('validity', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('PREPAID', 'prepaid plan type'), ('POSTPAID', 'postpaid plan type'), ('DONGLE', 'dongle plan type')], max_length=50)),
                ('data_remaining', models.IntegerField(default=0)),
                ('calls_remaining', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=5)),
                ('dob', models.DateField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('active_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='voizdata.Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='voizdata.LoginData')),
            ],
        ),
        migrations.AddField(
            model_name='logindata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='voizdata.Profile'),
        ),
    ]
