# Generated by Django 2.2.4 on 2019-08-10 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('prepaid-plan-type', 'PREPAID'), ('postpaid-plan-type', 'POSTPAID'), ('dongle-plan-type', 'DONGLE')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.BigIntegerField(default=600001)),
                ('choose_number', models.CharField(choices=[('9876543210', 9876543210), ('7871180868', 7871180868), ('7871180867', 7871180867), ('7871180866', 7871180866), ('7871180865', 7871180865)], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('prepaid-plan-type', 'PREPAID'), ('postpaid-plan-type', 'POSTPAID'), ('dongle-plan-type', 'DONGLE')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('validity', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10)),
                ('amount', models.IntegerField(default=0)),
                ('time_recharged', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('prepaid-plan-type', 'PREPAID'), ('postpaid-plan-type', 'POSTPAID'), ('dongle-plan-type', 'DONGLE')], max_length=100)),
                ('dob', models.DateField(verbose_name='DOB')),
                ('last_login', models.DateTimeField(verbose_name='Last_Login')),
                ('active_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='voizdata.Plan')),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login', to='voizdata.User')),
            ],
        ),
    ]
