# Generated by Django 2.2.4 on 2019-08-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voizdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledata',
            name='username',
            field=models.CharField(default='user', max_length=150),
            preserve_default=False,
        ),
    ]
