# Generated by Django 2.2.4 on 2019-08-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voizdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recharge',
            name='time_recharged',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
