# Generated by Django 2.2.3 on 2019-08-03 12:17

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('voizdata', '0002_remove_logindata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('prepaid plan type', 'PREPAID'), ('postpaid plan type', 'POSTPAID'), ('dongle plan type', 'DONGLE')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(max_length=100, verbose_name=django.db.models.fields.related.ForeignKey),
        ),
    ]
