# Generated by Django 2.2.4 on 2019-08-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voizdata', '0002_auto_20190806_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledata',
            name='dob',
            field=models.DateField(verbose_name='DOB'),
        ),
        migrations.AlterField(
            model_name='profiledata',
            name='last_login',
            field=models.DateTimeField(verbose_name='Last_Login'),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='time_recharged',
            field=models.DateTimeField(),
        ),
    ]
