# Generated by Django 2.2.4 on 2019-08-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voizdata', '0003_auto_20190803_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('prepaid-plan-type', 'PREPAID'), ('postpaid-plan-type', 'POSTPAID'), ('dongle-plan-type', 'DONGLE')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(max_length=100),
        ),
    ]
