# Generated by Django 2.2.4 on 2019-08-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voizdata', '0004_auto_20190805_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('prepaid-plan-type', 'PREPAID'), ('postpaid-plan-type', 'POSTPAID'), ('dongle-plan-type', 'DONGLE')], max_length=100),
        ),
    ]
