# Generated by Django 2.2.4 on 2019-08-05 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voizdata', '0005_auto_20190805_1428'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='ProfileData',
        ),
    ]
