# Generated by Django 2.2.4 on 2019-08-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_dongleform_feedback_postform_preform'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge',
            name='pid',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
